# vim:ft=ansible:
---
- hosts: all
  become: yes

  vars_files:
    - default.yml
    - vars/mysql.yml
    - vars/apache.yml
    - vars/php.yml
    - vars/nodejs.yml

  pre_tasks:
    - name: Install base packages and set OS vars
      include_tasks: tasks/base.yml

  roles:
    - geerlingguy.firewall
    - geerlingguy.repo-remi
    - geerlingguy.mysql
    - geerlingguy.ntp
    - geerlingguy.git
    - geerlingguy.apache
    - geerlingguy.php-versions
    - geerlingguy.php
    - geerlingguy.php-mysql
    - geerlingguy.apache-php-fpm
    - geerlingguy.composer

    #  Conditionally-installed roles.
    - { role: geerlingguy.redis, when: '"redis" in installed_extras'  }
    - { role: vpeltot.beanstalkd, when: '"beanstalkd" in installed_extras'  }
    - { role: ScorpionResponse.supervisord, when: '"supervisord" in installed_extras', become: yes  }
    - { role: geerlingguy.php-xdebug, when: '"xdebug" in installed_extras'  }
    - { role: geerlingguy.nodejs, when: '"nodejs" in installed_extras'  }

  tasks:
    - name: Link supervisord to /usr/local/bin/supervisord
      file:
        src: "/usr/bin/supervisord"
        dest: "/usr/local/bin/supdervisord"
        state: link
      when:
        - '"supervisord" in installed_extras'
      notify:
          - start supervisord
